global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api_gateway:8080']
    metrics_path: /metrics

  - job_name: 'data_simulator'
    static_configs:
      - targets: ['data_simulator:8000']
    metrics_path: /metrics

  - job_name: 'cashflow_predictor'
    static_configs:
      - targets: ['cashflow_predictor:8002']
    metrics_path: /metrics

  - job_name: 'cost_analyzer'
    static_configs:
      - targets: ['cost_analyzer:8001']
    metrics_path: /metrics

  - job_name: 'compliance_checker'
    static_configs:
      - targets: ['compliance_checker:8003']
    metrics_path: /metrics
