apiVersion: v1
kind: Secret
metadata:
  name: merchant-analytics-secrets
  namespace: merchant-analytics
type: Opaque
stringData:
  mongodb-uri: "mongodb://mongodb.merchant-analytics:27017/merchant_analytics?retryWrites=true&w=majority"
  redis-url: "redis://redis.merchant-analytics:6379/0"
  rabbitmq-uri: "amqp://guest:guest@rabbitmq.merchant-analytics:5672/"
  jwt-secret: "${JWT_SECRET}" 