global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'merchant-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gateway:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'merchant-gateway'

  - job_name: 'merchant-cashflow'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cashflow:8001']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'merchant-cashflow'

  - job_name: 'merchant-cost'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cost:8002']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'merchant-cost'

  - job_name: 'merchant-compliance'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['compliance:8003']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'merchant-compliance' 